import type { Category, Shop, Product, Review, Profile } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Electronics', slug: 'electronics', icon: 'Smartphone', parent_id: null, commission_rate: 10, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-2', name: 'Fashion', slug: 'fashion', icon: 'Shirt', parent_id: null, commission_rate: 12, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-3', name: 'Home & Living', slug: 'home-living', icon: 'Sofa', parent_id: null, commission_rate: 8, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-4', name: 'Sports & Fitness', slug: 'sports', icon: 'Dumbbell', parent_id: null, commission_rate: 10, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-5', name: 'Beauty & Personal Care', slug: 'beauty', icon: 'Heart', parent_id: null, commission_rate: 15, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-6', name: 'Watches', slug: 'watches', icon: 'Watch', parent_id: null, commission_rate: 14, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-7', name: 'Computers & Laptops', slug: 'laptops', icon: 'Laptop', parent_id: null, commission_rate: 8, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-8', name: 'Kitchen & Dining', slug: 'kitchen', icon: 'Utensils', parent_id: null, commission_rate: 10, created_at: '2026-01-01T00:00:00Z' },
];

export const INITIAL_SHOPS: Shop[] = [
  {
    id: 'shop-1',
    owner_id: 'vendor-1',
    name: 'Aura Sound & Tech',
    slug: 'aura-sound-tech',
    description: 'Pioneering high-fidelity acoustic gear and cutting-edge personal computing electronics.',
    logo_url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=300&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=1200&auto=format&fit=crop&q=80',
    status: 'approved',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'shop-2',
    owner_id: 'vendor-2',
    name: 'Nordic Habitat Co.',
    slug: 'nordic-habitat',
    description: 'Minimalist Scandinavian home decor, ergonomic office essentials, and artisanal homeware.',
    logo_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=300&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&auto=format&fit=crop&q=80',
    status: 'approved',
    created_at: '2026-01-02T00:00:00Z',
  },
  {
    id: 'shop-3',
    owner_id: 'vendor-3',
    name: 'Urban Atelier',
    slug: 'urban-atelier',
    description: 'Sustainably crafted luxury apparel, heavyweight basics, and refined everyday tailoring.',
    logo_url: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=300&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&auto=format&fit=crop&q=80',
    status: 'approved',
    created_at: '2026-01-03T00:00:00Z',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    shop_id: 'shop-1',
    category_id: 'cat-1',
    name: 'Aura Studio ANC Wireless Headphones',
    slug: 'aura-studio-anc-wireless-headphones',
    description: 'Experience pure sonic immersion with custom 40mm bio-cellulose drivers, hybrid active noise cancellation, ambient transparency mode, and ultra-soft memory foam earcups with 45 hours of playback.',
    price: 199.99,
    compare_price: 279.99,
    brand: 'AuraSound',
    rating: 4.88,
    rating_count: 142,
    status: 'active',
    created_at: '2026-01-10T00:00:00Z',
    images: [
      { id: 'img-1-1', product_id: 'prod-1', url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80', position: 0 },
      { id: 'img-1-2', product_id: 'prod-1', url: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&auto=format&fit=crop&q=80', position: 1 },
    ],
    variations: [
      { id: 'var-1-1', product_id: 'prod-1', color: 'Midnight Black', size: 'Standard', sku: 'AURA-ANC-BLK', stock: 35, price_adjustment: 0 },
      { id: 'var-1-2', product_id: 'prod-1', color: 'Cloud Silver', size: 'Standard', sku: 'AURA-ANC-SLV', stock: 24, price_adjustment: 0 },
    ],
  },
  {
    id: 'prod-2',
    shop_id: 'shop-1',
    category_id: 'cat-6',
    name: 'Aura Horizon Titanium Smartwatch',
    slug: 'aura-horizon-titanium-smartwatch',
    description: 'Precision aerospace-grade titanium case with sapphire crystal glass, 1.43" Ultra AMOLED always-on display, dual-band GPS, multi-sport tracking, and 14-day battery life.',
    price: 249.00,
    compare_price: 329.00,
    brand: 'Aura Chrono',
    rating: 4.92,
    rating_count: 98,
    status: 'active',
    created_at: '2026-01-12T00:00:00Z',
    images: [
      { id: 'img-2-1', product_id: 'prod-2', url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80', position: 0 },
      { id: 'img-2-2', product_id: 'prod-2', url: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&auto=format&fit=crop&q=80', position: 1 },
    ],
    variations: [
      { id: 'var-2-1', product_id: 'prod-2', color: 'Brushed Titanium', size: '44mm', sku: 'AURA-HORIZ-44', stock: 18, price_adjustment: 0 },
      { id: 'var-2-2', product_id: 'prod-2', color: 'Space Black Titanium', size: '44mm', sku: 'AURA-HORIZ-SB', stock: 22, price_adjustment: 15 },
    ],
  },
  {
    id: 'prod-3',
    shop_id: 'shop-2',
    category_id: 'cat-3',
    name: 'Ergonomic Executive High-Back Chair',
    slug: 'ergonomic-executive-high-back-chair',
    description: 'Engineered for all-day focus and spinal alignment. Features dynamic reactive lumbar support, 4D adjustable armrests, breathable dual-layer mesh, and smooth-glide caster wheels.',
    price: 219.00,
    compare_price: 299.00,
    brand: 'Nordic Ergo',
    rating: 4.79,
    rating_count: 215,
    status: 'active',
    created_at: '2026-01-15T00:00:00Z',
    images: [
      { id: 'img-3-1', product_id: 'prod-3', url: 'https://images.unsplash.com/photo-1580481077197-22f36bfb1689?w=800&auto=format&fit=crop&q=80', position: 0 },
      { id: 'img-3-2', product_id: 'prod-3', url: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?w=800&auto=format&fit=crop&q=80', position: 1 },
    ],
    variations: [
      { id: 'var-3-1', product_id: 'prod-3', color: 'Onyx Black', size: 'Standard', sku: 'ERGO-CHAIR-BLK', stock: 14, price_adjustment: 0 },
      { id: 'var-3-2', product_id: 'prod-3', color: 'Stone Grey', size: 'Standard', sku: 'ERGO-CHAIR-GRY', stock: 9, price_adjustment: 0 },
    ],
  },
  {
    id: 'prod-4',
    shop_id: 'shop-3',
    category_id: 'cat-2',
    name: 'Heavyweight 500GSM Organic Hoodie',
    slug: 'heavyweight-500gsm-organic-hoodie',
    description: 'Custom-milled 100% GOTS-certified French terry organic cotton. Cut with dropped shoulders, deep double-lined hood, seamless kangaroo pocket, and durable ribbed trims.',
    price: 75.00,
    compare_price: 98.00,
    brand: 'Urban Atelier',
    rating: 4.65,
    rating_count: 87,
    status: 'active',
    created_at: '2026-01-18T00:00:00Z',
    images: [
      { id: 'img-4-1', product_id: 'prod-4', url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80', position: 0 },
      { id: 'img-4-2', product_id: 'prod-4', url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80', position: 1 },
    ],
    variations: [
      { id: 'var-4-1', product_id: 'prod-4', color: 'Washed Olive', size: 'M', sku: 'HOOD-OLV-M', stock: 25, price_adjustment: 0 },
      { id: 'var-4-2', product_id: 'prod-4', color: 'Washed Olive', size: 'L', sku: 'HOOD-OLV-L', stock: 30, price_adjustment: 0 },
      { id: 'var-4-3', product_id: 'prod-4', color: 'Washed Black', size: 'M', sku: 'HOOD-BLK-M', stock: 19, price_adjustment: 0 },
      { id: 'var-4-4', product_id: 'prod-4', color: 'Washed Black', size: 'L', sku: 'HOOD-BLK-L', stock: 22, price_adjustment: 0 },
    ],
  },
  {
    id: 'prod-5',
    shop_id: 'shop-1',
    category_id: 'cat-7',
    name: 'AuraBook Pro 16" OLED Ultra',
    slug: 'aurabook-pro-16-oled-ultra',
    description: 'Pro workstation powerhouse with 3.2K 120Hz OLED HDR display, 14-core processor, 32GB LPDDR5X RAM, 1TB PCIe 4.0 SSD, vapor chamber cooling, and magnetic fast charging.',
    price: 1499.00,
    compare_price: 1799.00,
    brand: 'Aura Compute',
    rating: 4.95,
    rating_count: 64,
    status: 'active',
    created_at: '2026-01-20T00:00:00Z',
    images: [
      { id: 'img-5-1', product_id: 'prod-5', url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80', position: 0 },
      { id: 'img-5-2', product_id: 'prod-5', url: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&auto=format&fit=crop&q=80', position: 1 },
    ],
    variations: [
      { id: 'var-5-1', product_id: 'prod-5', color: 'Space Grey', size: '32GB / 1TB', sku: 'AB-PRO16-32', stock: 12, price_adjustment: 0 },
    ],
  },
  {
    id: 'prod-6',
    shop_id: 'shop-2',
    category_id: 'cat-8',
    name: 'Japanese 67-Layer Damascus Chef Knife 8"',
    slug: 'japanese-67-layer-damascus-chef-knife',
    description: 'Hand-forged Japanese VG-10 super steel core clad with 66 micro-layers of stainless Damascus. 15-degree razor edge with moisture-resistant octagonal Pakkawood handle.',
    price: 89.00,
    compare_price: 125.00,
    brand: 'Kurogane Blade',
    rating: 4.86,
    rating_count: 176,
    status: 'active',
    created_at: '2026-01-22T00:00:00Z',
    images: [
      { id: 'img-6-1', product_id: 'prod-6', url: 'https://images.unsplash.com/photo-1593618998160-e34014e67546?w=800&auto=format&fit=crop&q=80', position: 0 },
    ],
    variations: [
      { id: 'var-6-1', product_id: 'prod-6', color: 'Walnut & Resin', size: '8 Inch', sku: 'KNIFE-DAMAS-8', stock: 40, price_adjustment: 0 },
    ],
  },
  {
    id: 'prod-7',
    shop_id: 'shop-2',
    category_id: 'cat-4',
    name: 'Cast Iron Competition Kettlebell 24kg',
    slug: 'cast-iron-competition-kettlebell-24kg',
    description: 'Precision gravity-cast single-piece virgin iron without fillers or welds. Smooth flat machined bottom, color-coded green handle ring, and matte powder-coat finish.',
    price: 85.00,
    compare_price: 110.00,
    brand: 'Apex Strength',
    rating: 4.74,
    rating_count: 53,
    status: 'active',
    created_at: '2026-01-25T00:00:00Z',
    images: [
      { id: 'img-7-1', product_id: 'prod-7', url: 'https://images.unsplash.com/photo-1586401100295-7a8096fd231a?w=800&auto=format&fit=crop&q=80', position: 0 },
    ],
    variations: [
      { id: 'var-7-1', product_id: 'prod-7', color: 'Competition Green', size: '24 kg (53 lbs)', sku: 'KB-COMP-24', stock: 20, price_adjustment: 0 },
      { id: 'var-7-2', product_id: 'prod-7', color: 'Competition Blue', size: '16 kg (35 lbs)', sku: 'KB-COMP-16', stock: 15, price_adjustment: -20 },
    ],
  },
  {
    id: 'prod-8',
    shop_id: 'shop-3',
    category_id: 'cat-5',
    name: 'Botanical Vitamin C Radiance Serum 50ml',
    slug: 'botanical-vitamin-c-radiance-serum',
    description: 'Concentrated 15% stabilized L-ascorbic acid fortified with plant hyaluronic acid, ferulic acid, and cold-pressed wild rosehip extract for intense brightening and barrier support.',
    price: 38.00,
    compare_price: 52.00,
    brand: 'Lumina Botanicals',
    rating: 4.82,
    rating_count: 129,
    status: 'active',
    created_at: '2026-01-28T00:00:00Z',
    images: [
      { id: 'img-8-1', product_id: 'prod-8', url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&auto=format&fit=crop&q=80', position: 0 },
    ],
    variations: [
      { id: 'var-8-1', product_id: 'prod-8', color: 'Amber Glass', size: '50 ml', sku: 'LUM-SERUM-50', stock: 50, price_adjustment: 0 },
    ],
  },
  {
    id: 'prod-9',
    shop_id: 'shop-1',
    category_id: 'cat-1',
    name: 'Aura Soundbar Cinema Pro with Subwoofer',
    slug: 'aura-soundbar-cinema-pro',
    description: '3.1.2 channel Dolby Atmos soundbar with upward-firing speakers, wireless 8" down-firing subwoofer, eARC HDMI pass-through, and Bluetooth 5.3 streaming.',
    price: 329.00,
    compare_price: 449.00,
    brand: 'AuraSound',
    rating: 4.85,
    rating_count: 73,
    status: 'active',
    created_at: '2026-01-30T00:00:00Z',
    images: [
      { id: 'img-9-1', product_id: 'prod-9', url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80', position: 0 },
    ],
    variations: [
      { id: 'var-9-1', product_id: 'prod-9', color: 'Graphite Black', size: 'Complete Set', sku: 'SBAR-PRO-BLK', stock: 16, price_adjustment: 0 },
    ],
  },
  {
    id: 'prod-10',
    shop_id: 'shop-2',
    category_id: 'cat-8',
    name: 'Artisan Ceramic Pour-Over Coffee Set',
    slug: 'artisan-ceramic-pour-over-coffee-set',
    description: 'Handcrafted stoneware dripper with spiral interior ribs paired with an 800ml heat-resistant borosilicate glass server and bamboo insulation collar.',
    price: 34.00,
    compare_price: 45.00,
    brand: 'Nordic Habitat',
    rating: 4.91,
    rating_count: 88,
    status: 'active',
    created_at: '2026-02-02T00:00:00Z',
    images: [
      { id: 'img-10-1', product_id: 'prod-10', url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80', position: 0 },
    ],
    variations: [
      { id: 'var-10-1', product_id: 'prod-10', color: 'Matte Sand', size: '02 (1-4 cups)', sku: 'COFFEE-SET-SND', stock: 32, price_adjustment: 0 },
    ],
  },
];

// Attach shops and categories to products
INITIAL_PRODUCTS.forEach((p) => {
  p.shop = INITIAL_SHOPS.find((s) => s.id === p.shop_id);
  p.category = INITIAL_CATEGORIES.find((c) => c.id === p.category_id);
});

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    product_id: 'prod-1',
    user_id: 'cust-1',
    rating: 5,
    comment: 'Sound clarity is breathtaking. Noise cancellation cuts out train and flight hum completely. Super comfortable on long sessions!',
    created_at: '2026-02-10T14:20:00Z',
    profile: { id: 'cust-1', full_name: 'David Reynolds', role: 'customer', phone: '', avatar_url: '', created_at: '2026-01-01T00:00:00Z' },
  },
  {
    id: 'rev-2',
    product_id: 'prod-1',
    user_id: 'cust-2',
    rating: 5,
    comment: 'The battery easily lasts all week. Beautiful packaging and build quality.',
    created_at: '2026-02-15T09:12:00Z',
    profile: { id: 'cust-2', full_name: 'Elena Rostova', role: 'customer', phone: '', avatar_url: '', created_at: '2026-01-02T00:00:00Z' },
  },
  {
    id: 'rev-3',
    product_id: 'prod-2',
    user_id: 'cust-3',
    rating: 5,
    comment: 'The titanium finish feels ultra-premium. Heart rate and GPS are spot-on during my morning runs.',
    created_at: '2026-02-18T16:45:00Z',
    profile: { id: 'cust-3', full_name: 'Marcus Thorne', role: 'customer', phone: '', avatar_url: '', created_at: '2026-01-03T00:00:00Z' },
  },
];

export const DEMO_PROFILES: Profile[] = [
  { id: 'user-customer-demo', full_name: 'Aura Customer', role: 'customer', phone: '+1234567890', avatar_url: '', created_at: '2026-01-01T00:00:00Z', status: 'active', country_code: 'US' },
  { id: 'user-vendor-demo', full_name: 'Vendor Partner', role: 'vendor', phone: '+1987654321', avatar_url: '', created_at: '2026-01-01T00:00:00Z', status: 'active', country_code: 'US' },
  { id: 'user-admin-demo', full_name: 'Marketplace Administrator', role: 'admin', phone: '+1555000111', avatar_url: '', created_at: '2026-01-01T00:00:00Z', status: 'active', country_code: 'US' },
];
