import { useI18n } from '@/contexts/I18nContext';
import { useEffect, useState, useCallback } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Shield, Store, ShoppingBag, Layers, Check, X, Loader2, DollarSign, Package, Users, FileCheck, Settings, Eye, Bell } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/lib/supabase';
import type { Shop, Order, Category } from '@/lib/types';
import { formatPriceSimple, formatDate, classNames, slugify } from '@/lib/utils';

type Tab='overview'|'vendors'|'orders'|'categories'|'settings'|'finance'|'audit';
export default function AdminPanel(){
  const { t } = useI18n();
 const {user,profile}=useAuth(); const navigate=useNavigate(); const [tab,setTab]=useState<Tab>('overview');
 useEffect(()=>{if(!user) navigate('/signin');},[user,navigate]);
 if(!user)return null;
 if(profile?.role!=='admin') return <div className="min-h-screen bg-gray-50 flex items-center justify-center p-6"><div className="bg-white rounded-2xl border p-8 text-center"><Shield className="mx-auto text-gray-300 mb-4" size={48}/><h1 className="text-xl font-bold">{t('admin.accessRequired')}</h1><p className="text-gray-500 mt-2 mb-5">{t('admin.accessText')}</p><Link to="/" className="px-5 py-2 rounded-lg bg-sky-500 text-white">{t('admin.backHome')}</Link></div></div>;
 const tabs=[['overview',t('admin.overview'),Shield],['vendors',t('admin.vendorKyc'),FileCheck],['orders',t('admin.orders'),ShoppingBag],['categories',t('admin.categoriesCommission'),Layers],['finance',t('admin.finance'),DollarSign],['audit',t('admin.audit'),Bell],['settings',t('admin.platformSettings'),Settings]] as const;
 return <div className="bg-gray-50 min-h-screen"><div className="max-w-7xl mx-auto px-4 py-6"><div className="bg-slate-900 rounded-2xl p-6 mb-6 text-white"><div className="flex items-center gap-3"><Shield size={28}/><div><h1 className="text-xl font-bold">{t('admin.controlPanel')}</h1><p className="text-sm text-gray-300">{t('admin.controlSubtitle')}</p></div></div></div><div className="flex gap-1 mb-6 overflow-x-auto border-b">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={classNames('flex items-center gap-2 px-4 py-3 text-sm font-medium border-b-2 whitespace-nowrap',tab===id?'border-sky-500 text-sky-600':'border-transparent text-gray-500')}><Icon size={17}/>{label}</button>)}</div>{tab==='overview'&&<Overview/>}{tab==='vendors'&&<Vendors/>}{tab==='orders'&&<Orders/>}{tab==='categories'&&<Categories/>}{tab==='settings'&&<SettingsTab/>}{tab==='finance'&&<FinanceTab/>}{tab==='audit'&&<AuditTab/>}</div></div>
}
function Overview(){const { t } = useI18n();const [s,setS]=useState({vendors:0,pending:0,orders:0,revenue:0,products:0,customers:0}); useEffect(()=>{(async()=>{const [v,p,o,pr,c]=await Promise.all([supabase.from('shops').select('id',{count:'exact',head:true}),supabase.from('shops').select('id',{count:'exact',head:true}).eq('status','pending'),supabase.from('orders').select('total'),supabase.from('products').select('id',{count:'exact',head:true}),supabase.from('profiles').select('id',{count:'exact',head:true}).eq('role','customer')]);const orders=(o.data as Order[])??[];setS({vendors:v.count??0,pending:p.count??0,orders:orders.length,revenue:orders.reduce((a,x)=>a+Number(x.total||0),0),products:pr.count??0,customers:c.count??0});})()},[]); const cards=[[t('admin.vendors'),s.vendors,Store],[t('admin.pending'),s.pending,FileCheck],[t('admin.orders'),s.orders,ShoppingBag],[t('admin.revenue'),formatPriceSimple(s.revenue),DollarSign],[t('admin.products'),s.products,Package],[t('admin.customers'),s.customers,Users]] as const; return <div className="grid grid-cols-2 lg:grid-cols-6 gap-4">{cards.map(([l,v,I])=><div className="bg-white rounded-xl border p-5" key={l}><I size={19} className="text-sky-500 mb-3"/><p className="text-xs text-gray-500">{l}</p><p className="text-2xl font-bold">{v}</p></div>)}</div>}
function Vendors(){const { t } = useI18n();const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [rates,setRates]=useState<Record<string,string>>({});const load=useCallback(async()=>{const {data}=await supabase.from('shops').select('*').order('created_at',{ascending:false});setRows(data??[]);setLoading(false)},[]);useEffect(()=>{load()},[load]);const review=async(id:string,status:'approved'|'rejected'|'pending')=>{const r=await supabase.functions.invoke('admin-vendor-review',{body:{vendor_id:id,status,commission_rate:Number(rates[id] ?? 10)}});if(r.error||r.data?.ok===false)alert(r.error?.message||r.data?.error||'Review failed');else load()};const doc=async(id:string)=>{const r=await supabase.functions.invoke('admin-vendor-review',{body:{action:'document_url',vendor_id:id}});if(r.data?.url)window.open(r.data.url,'_blank','noopener,noreferrer');else alert(r.data?.error||r.error?.message||'Document unavailable')};if(loading)return <div className="py-16 text-center text-gray-400">{t('common.loading')}</div>;return <div className="space-y-3">{rows.map(s=><div key={s.id} className="bg-white rounded-xl border p-5 flex flex-wrap items-center gap-4 justify-between"><div><p className="font-bold">{s.name}</p><p className="text-xs text-gray-500">{formatDate(s.created_at)} · {s.status}</p></div><div className="flex items-center gap-2 flex-wrap justify-end"><label className="text-xs text-gray-500">{t('admin.commission')} <input value={rates[s.owner_id] ?? '10'} onChange={e=>setRates({...rates,[s.owner_id]:e.target.value})} type="number" min="0" max="100" step="0.01" className="w-20 border rounded-lg px-2 py-1 ms-1" />%</label><button onClick={()=>doc(s.owner_id)} className="px-3 py-2 border rounded-lg text-sm"><Eye size={15} className="inline me-1"/>{t('admin.kyc')}</button>{s.status==='pending'&&<button onClick={()=>review(s.owner_id,'approved')} className="px-3 py-2 bg-emerald-500 text-white rounded-lg text-sm"><Check size={15} className="inline me-1"/>{t('admin.approve')}</button>}{s.status!=='rejected'&&<button onClick={()=>review(s.owner_id,'rejected')} className="px-3 py-2 bg-rose-500 text-white rounded-lg text-sm"><X size={15} className="inline me-1"/>{t('admin.reject')}</button>}{s.status==='suspended'&&<button onClick={()=>review(s.owner_id,'approved')} className="px-3 py-2 bg-sky-500 text-white rounded-lg text-sm">{t('admin.reinstate')}</button>}</div></div>)}</div>}
function Orders(){const { t } = useI18n();const [rows,setRows]=useState<Order[]>([]);const load=useCallback(async()=>{const {data}=await supabase.from('orders').select('*').order('created_at',{ascending:false});setRows((data as Order[])??[])},[]);useEffect(()=>{load()},[load]);const update=async(id:string,status:string)=>{const {error}=await supabase.from('orders').update({status}).eq('id',id);if(error)alert(error.message);else load()};return <div className="bg-white rounded-xl border overflow-x-auto"><table className="w-full"><thead className="bg-gray-50"><tr>{[t('common.order'),t('common.customer'),t('common.date'),t('common.total'),t('common.status')].map(x=><th className="text-start text-xs px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(o=><tr key={o.id} className="border-t"><td className="px-4 py-3 font-mono text-sm">#{o.id.slice(0,8)}</td><td className="px-4 py-3 text-sm">{o.customer_name}</td><td className="px-4 py-3 text-sm">{formatDate(o.created_at)}</td><td className="px-4 py-3 font-bold">{formatPriceSimple(o.total)}</td><td className="px-4 py-3"><select value={o.status} onChange={e=>update(o.id,e.target.value)} className="border rounded-lg px-2 py-1 text-sm"><option value="pending">{t('common.pending')}</option><option value="confirmed">{t('orders.confirmed')}</option><option value="shipped">{t('orders.shipped')}</option><option value="delivered">{t('orders.delivered')}</option><option value="cancelled">{t('common.rejected')}</option></select></td></tr>)}</tbody></table>{rows.length===0&&<p className="p-10 text-center text-gray-500">{t('admin.noOrders')}</p>}</div>}
function Categories(){const { t } = useI18n();const [rows,setRows]=useState<Category[]>([]);const [name,setName]=useState('');const [rate,setRate]=useState('10');const load=useCallback(async()=>{const {data}=await supabase.from('categories').select('*').order('name');setRows((data as Category[])??[])},[]);useEffect(()=>{load()},[load]);const add=async()=>{if(!name.trim())return;const {error}=await supabase.from('categories').insert({name:name.trim(),slug:slugify(name)+'-'+Date.now().toString(36),icon:'Package',commission_rate:Math.min(100,Math.max(0,Number(rate)||10))});if(error)alert(error.message);else{name&&setName('');setRate('10');load()}};return <div><div className="bg-white rounded-xl border p-4 mb-4 flex flex-wrap gap-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder={t('admin.categoryName')} className="h-10 border rounded-lg px-3"/><input type="number" min="0" max="100" value={rate} onChange={e=>setRate(e.target.value)} className="h-10 w-24 border rounded-lg px-3"/><button onClick={add} className="h-10 px-4 rounded-lg bg-sky-500 text-white">{t('admin.add')}</button></div><div className="bg-white rounded-xl border overflow-hidden"><table className="w-full"><thead className="bg-gray-50"><tr><th className="text-start px-4 py-3 text-xs">{t('vendor.category')}</th><th className="text-start px-4 py-3 text-xs">{t('admin.commissionPercent')}</th></tr></thead><tbody>{rows.map(c=><tr className="border-t" key={c.id}><td className="px-4 py-3">{c.name}</td><td className="px-4 py-3"><input defaultValue={c.commission_rate} type="number" min="0" max="100" step="0.5" onBlur={async e=>{const n=Number(e.target.value);if(Number.isFinite(n)){await supabase.from('categories').update({commission_rate:n}).eq('id',c.id);load()}}} className="w-24 border rounded-lg px-2 py-1"/></td></tr>)}</tbody></table></div></div>}
function SettingsTab(){const { t } = useI18n();const [settings,setSettings]=useState<any>({default_commission_rate:10,default_currency:'USD',support_cod:true,support_stripe:false,support_paypal:false});const [saving,setSaving]=useState(false);useEffect(()=>{supabase.from('platform_settings').select('value').eq('key','marketplace').maybeSingle().then(({data})=>{if(data?.value)setSettings((x:any)=>({...x,...data.value}))})},[]);const save=async()=>{setSaving(true);const {error}=await supabase.from('platform_settings').upsert({key:'marketplace',value:settings,is_public:true});setSaving(false);if(error)alert(error.message);else alert(t('admin.settingsSaved'))};return <div className="bg-white rounded-xl border p-6 max-w-2xl"><h2 className="font-bold text-lg mb-5">{t('admin.platformSettings')}</h2><div className="grid sm:grid-cols-2 gap-4"><label className="text-sm">{t('admin.defaultCommission')}<input className="mt-1 w-full border rounded-lg h-10 px-3" type="number" min="0" max="100" value={settings.default_commission_rate} onChange={e=>setSettings({...settings,default_commission_rate:Number(e.target.value)})}/></label><label className="text-sm">{t('admin.defaultCurrency')}<input className="mt-1 w-full border rounded-lg h-10 px-3" value={settings.default_currency} onChange={e=>setSettings({...settings,default_currency:e.target.value.toUpperCase()})}/></label></div><div className="space-y-3 mt-5">{(['support_cod','support_stripe','support_paypal'] as const).map(k=><label key={k} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!settings[k]} onChange={e=>setSettings({...settings,[k]:e.target.checked})}/>{k.replace('support_','').toUpperCase()} {t('admin.enabled')}</label>)}</div><p className="text-xs text-gray-500 mt-5">{t('admin.secretNote')}</p><button onClick={save} disabled={saving} className="mt-6 px-5 h-10 rounded-lg bg-sky-500 text-white disabled:opacity-50">{saving?t('admin.saving'):t('admin.saveSettings')}</button></div>}

function FinanceTab(){const { t } = useI18n();
 const [withdrawals,setWithdrawals]=useState<any[]>([]); const [refunds,setRefunds]=useState<any[]>([]); const [disputes,setDisputes]=useState<any[]>([]);
 const load=useCallback(async()=>{const [w,r,d]=await Promise.all([supabase.from('withdrawal_requests').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('refund_requests').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('disputes').select('*').order('created_at',{ascending:false}).limit(100)]);setWithdrawals(w.data??[]);setRefunds(r.data??[]);setDisputes(d.data??[]);},[]);
 useEffect(()=>{load()},[load]);
 const update=async(table:string,id:string,status:string)=>{const {error}=await supabase.from(table).update({status,reviewed_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else load()};
 return <div className="space-y-6"><section className="bg-white rounded-xl border p-5"><h2 className="font-bold mb-4">{t('admin.withdrawalRequests')}</h2>{withdrawals.length===0?<p className="text-sm text-gray-500">{t('admin.noWithdrawals')}</p>:<div className="space-y-2">{withdrawals.map(x=><div key={x.id} className="flex flex-wrap justify-between gap-3 border-b py-3"><span>{x.vendor_id.slice(0,8)} · {x.amount} {x.currency}</span><span className="flex gap-2"><b className="text-xs self-center">{x.status}</b>{x.status==='pending'&&<><button onClick={()=>update('withdrawal_requests',x.id,'approved')} className="px-2 py-1 text-xs bg-sky-500 text-white rounded">{t('admin.approve')}</button><button onClick={()=>update('withdrawal_requests',x.id,'rejected')} className="px-2 py-1 text-xs bg-rose-500 text-white rounded">{t('admin.reject')}</button></>}</span></div>)}</div>}</section><section className="bg-white rounded-xl border p-5"><h2 className="font-bold mb-4">{t('admin.refundRequests')}</h2>{refunds.length===0?<p className="text-sm text-gray-500">{t('admin.noRefunds')}</p>:refunds.map(x=><div key={x.id} className="flex flex-wrap justify-between gap-3 border-b py-3"><span>{x.order_id.slice(0,8)} · {x.amount}</span><span className="flex gap-2"><b className="text-xs self-center">{x.status}</b>{x.status==='pending'&&<><button onClick={()=>update('refund_requests',x.id,'approved')} className="px-2 py-1 text-xs bg-sky-500 text-white rounded">{t('admin.approve')}</button><button onClick={()=>update('refund_requests',x.id,'rejected')} className="px-2 py-1 text-xs bg-rose-500 text-white rounded">{t('admin.reject')}</button></>}</span></div>)}</section><section className="bg-white rounded-xl border p-5"><h2 className="font-bold mb-4">{t('admin.disputes')}</h2>{disputes.length===0?<p className="text-sm text-gray-500">{t('admin.noDisputes')}</p>:disputes.map(x=><div key={x.id} className="flex justify-between border-b py-3"><span>{x.order_id.slice(0,8)} · {x.reason}</span><b className="text-xs">{x.status}</b></div>)}</section></div>
}

function AuditTab(){const { t } = useI18n();const [rows,setRows]=useState<any[]>([]);useEffect(()=>{supabase.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(200).then(({data})=>setRows(data??[]))},[]);return <div className="bg-white rounded-xl border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50"><tr><th className="text-start p-3">{t('admin.time')}</th><th className="text-start p-3">{t('admin.action')}</th><th className="text-start p-3">{t('admin.entity')}</th><th className="text-start p-3">{t('admin.metadata')}</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} className="border-t"><td className="p-3">{formatDate(x.created_at)}</td><td className="p-3 font-medium">{x.action}</td><td className="p-3">{x.entity_type} {x.entity_id?.slice?.(0,8)}</td><td className="p-3 text-xs text-gray-500 max-w-md truncate">{JSON.stringify(x.metadata)}</td></tr>)}</tbody></table></div>}
